name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: kivy/buildozer:latest

    steps:
      - uses: actions/checkout@v4

      - name: Fix permissions and build
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: BratvaDPI-arm64
          path: bin/*.apk
