name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Flet APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Build APK via Flet
        run: |
          # Flet автоматически скачает Flutter SDK и Android SDK
          flet build apk --project-name BratvaDPI --org com.salvatorebonpinsiero.bratvadpi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BratvaDPI-App
          path: build/apk/app-release.apk
