name: Build APK Release

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: 

jobs:
  build:
    name: Build Flet APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet Pillow
          if [ ! -f requirements.txt ]; then 
            echo "flet" > requirements.txt
          fi

      - name: Prepare Assets
        run: |
          mkdir -p assets
          wget -O temp_logo.jpg "https://raw.githubusercontent.com/SalvatoreBonpinsiero/BratvaDPI/refs/heads/main/logo.jpg"
          python -c "from PIL import Image; Image.open('temp_logo.jpg').save('assets/icon.png')"
          rm temp_logo.jpg

      - name: Build APK via Flet
        run: yes | flet build apk -v --project bratvadpi --org com.salvatorebonpinsiero.bratvadpi

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BratvaDPI-Release
          path: build/apk/*.apk
